//console.log("Made it inside seed.js");

const { Pool } = require('pg');
const dbConn = require('./dbConn');
const pool = dbConn.getPool();

function runSeeder(pool, callback) {
    pool.connect((err, client, done) => {
        if (err) {
            console.log("Failed to connect to the database");
            console.log(err);
            return done();
        }
                                                                                                                        // Done                                                                                                                 Not downloading                                                                                                                    Done          
        //Run SEED SQL:
        pool.query(`INSERT INTO shoes (name, shoeid, price, gender, image, image_array, description, color_description, style, size_array) VALUES 
            ('Air Jordan 1 Mid', 1, '$125', 'Men''s Shoes', 'http://localhost:8000/images/shoe1/shoe1view1.webp' , ARRAY ['http://localhost:8000/images/shoe1/shoe1view1.webp', 'http://localhost:8000/images/shoe1/shoe1view2.webp', 'http://localhost:8000/images/shoe1/shoe1view3.webp', 'http://localhost:8000/images/shoe1/shoe1view4.webp', 'http://localhost:8000/images/shoe1/shoe1view5.webp', 'http://localhost:8000/images/shoe1/shoe1view6.webp', 'http://localhost:8000/images/shoe1/shoe1view7.webp', 'http://localhost:8000/images/shoe1/shoe1view8.webp'], 'Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colors and crisp leather give it a distinct identity.', 'Shown: Lucky Green/White/Black', 'Style: DQ8426-301', ARRAY ['M 7 / W 8.5','M 7.5 / W 9','M 8 / W 9.5','M 8.5 / W 10','M 9 / W 10.5','M 9.5 / W 11','M 10 / W 11.5','M 10.5 / W 12','M 11 / W 12.5','M 11.5 / W 13','M 12 / W 13.5','M 12.5 / W 14','M 13 / W 14.5','M 14 / W 15.5','M 15 / W 16.5','M 16 / W 17.5','M 17 / W 18.5','M 18 / W 19.5']),
            ('Air Jordan 1 Mid', 1, '$125', 'Men''s Shoes', 'http://localhost:8000/images/shoe2/shoe2view1.webp', ARRAY ['http://localhost:8000/images/shoe2/shoe2view1.webp', 'http://localhost:8000/images/shoe2/shoe2view2.webp', 'http://localhost:8000/images/shoe2/shoe2view3.webp', 'http://localhost:8000/images/shoe2/shoe2view4.webp', 'http://localhost:8000/images/shoe2/shoe2view5.webp', 'http://localhost:8000/images/shoe2/shoe2view6.webp', 'http://localhost:8000/images/shoe2/shoe2view7.webp', 'http://localhost:8000/images/shoe2/shoe2view8.webp'], 'Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colors and crisp leather give it a distinct identity.', 'Shown: Palomino/Wild Berry/White','Style: DQ8426-215', ARRAY ['M 7 / W 8.5','M 7.5 / W 9','M 8 / W 9.5','M 8.5 / W 10','M 9 / W 10.5','M 9.5 / W 11','M 10 / W 11.5','M 10.5 / W 12','M 11 / W 12.5','M 11.5 / W 13','M 12 / W 13.5','M 12.5 / W 14','M 13 / W 14.5','M 14 / W 15.5','M 15 / W 16.5','M 16 / W 17.5','M 17 / W 18.5','M 18 / W 19.5']),
            ('Air Jordan 1 Mid', 1, '$125', 'Men''s Shoes', 'http://localhost:8000/images/shoe3/shoe3view1.webp', ARRAY ['http://localhost:8000/images/shoe3/shoe3view1.webp', 'http://localhost:8000/images/shoe3/shoe3view2.webp', 'http://localhost:8000/images/shoe3/shoe3view3.webp', 'http://localhost:8000/images/shoe3/shoe3view4.webp', 'http://localhost:8000/images/shoe3/shoe3view5.webp', 'http://localhost:8000/images/shoe3/shoe3view6.webp', 'http://localhost:8000/images/shoe3/shoe3view7.webp', 'http://localhost:8000/images/shoe3/shoe3view8.webp'], 'You ready for your moment in the sun? Every time the AJ1 gets a remake you get the classic sneaker in new colors and textures for a fresh look with a familiar feel. Premium materials and accents give modern expression to an all-time favorite. Get out there and shine.', 'Shown: Game Royal/Phantom/White/Rush Orange', 'Style: FD1029-400', ARRAY ['M 3.5 / W 5','M 4 / W 5.5','M 4.5 / W 6','M 5 / W 6.5','M 5.5 / W 7','M 6 / W 7.5','M 6.5 / W 8','M 7 / W 8.5','M 7.5 / W 9','M 8 / W 9.5','M 8.5 / W 10','M 9 / W 10.5','M 9.5 / W 11','M 10 / W 11.5','M 10.5 / W 12','M 11 / W 12.5','M 11.5 / W 13','M 12 / W 13.5','M 12.5 / W 14','M 13 / W 14.5','M 14 / W 15.5','M 15 / W 16.5','M 16 / W 17.5','M 17 / W 18.5']),
            ('Air Jordan 1 Mid', 1, '$125', 'Men''s Shoes', 'http://localhost:8000/images/shoe4/shoe4view1.webp', ARRAY ['http://localhost:8000/images/shoe4/shoe4view1.webp', 'http://localhost:8000/images/shoe4/shoe4view2.webp', 'http://localhost:8000/images/shoe4/shoe4view3.webp', 'http://localhost:8000/images/shoe4/shoe4view4.webp', 'http://localhost:8000/images/shoe4/shoe4view5.webp', 'http://localhost:8000/images/shoe4/shoe4view6.webp', 'http://localhost:8000/images/shoe4/shoe4view7.webp', 'http://localhost:8000/images/shoe4/shoe4view8.webp'], 'Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colors and crisp leather give it a distinct identity.', 'Shown: Cement Grey/True Blue/White', 'Style: DQ8426-014', ARRAY ['M 7 / W 8.5','M 7.5 / W 9','M 8 / W 9.5','M 8.5 / W 10','M 9 / W 10.5','M 9.5 / W 11','M 10 / W 11.5','M 10.5 / W 12','M 11 / W 12.5','M 11.5 / W 13','M 12 / W 13.5','M 12.5 / W 14','M 13 / W 14.5','M 14 / W 15.5','M 15 / W 16.5','M 16 / W 17.5','M 17 / W 18.5','M 18 / W 19.5']),
            ('Air Jordan 1 Mid', 1, '$125', 'Men''s Shoes', 'http://localhost:8000/images/shoe5/shoe5view1.webp', ARRAY ['http://localhost:8000/images/shoe5/shoe5view1.webp', 'http://localhost:8000/images/shoe5/shoe5view2.webp', 'http://localhost:8000/images/shoe5/shoe5view3.webp', 'http://localhost:8000/images/shoe5/shoe5view4.webp', 'http://localhost:8000/images/shoe5/shoe5view5.webp', 'http://localhost:8000/images/shoe5/shoe5view6.webp', 'http://localhost:8000/images/shoe5/shoe5view7.webp', 'http://localhost:8000/images/shoe5/shoe5view8.webp'], 'Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colors and crisp leather give it a distinct identity.', 'Shown: Black/White/Fire Red', 'Style: DQ8426-060', ARRAY ['M 7 / W 8.5','M 7.5 / W 9','M 8 / W 9.5','M 8.5 / W 10','M 9 / W 10.5','M 9.5 / W 11','M 10 / W 11.5','M 10.5 / W 12','M 11 / W 12.5','M 11.5 / W 13','M 12 / W 13.5','M 12.5 / W 14','M 13 / W 14.5','M 14 / W 15.5','M 15 / W 16.5','M 16 / W 17.5','M 17 / W 18.5','M 18 / W 19.5']),
            ('Air Jordan 1 Mid', 1, '$93.97 24% off', 'Men''s Shoes', 'http://localhost:8000/images/shoe6/shoe6view1.webp', ARRAY ['http://localhost:8000/images/shoe6/shoe6view1.webp', 'http://localhost:8000/images/shoe6/shoe6view2.webp', 'http://localhost:8000/images/shoe6/shoe6view3.webp', 'http://localhost:8000/images/shoe6/shoe6view4.webp', 'http://localhost:8000/images/shoe6/shoe6view5.webp', 'http://localhost:8000/images/shoe6/shoe6view6.webp', 'http://localhost:8000/images/shoe6/shoe6view7.webp', 'http://localhost:8000/images/shoe6/shoe6view8.webp'], 'Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colors and crisp leather give it a distinct identity.', 'Shown: Dark Concord/White/Black/Taxi', 'Style: DQ8426-517', ARRAY ['M 7 / W 8.5','M 7.5 / W 9','M 8 / W 9.5','M 8.5 / W 10','M 9 / W 10.5','M 9.5 / W 11','M 10 / W 11.5','M 10.5 / W 12','M 11 / W 12.5','M 11.5 / W 13','M 12 / W 13.5','M 12.5 / W 14','M 13 / W 14.5','M 14 / W 15.5','M 15 / W 16.5','M 16 / W 17.5','M 17 / W 18.5','M 18 / W 19.5']),
            ('Air Jordan 1 Mid', 1, '$106.97 14% off','Men''s Shoes', 'http://localhost:8000/images/shoe7/shoe7view1.webp', ARRAY ['http://localhost:8000/images/shoe7/shoe7view1.webp', 'http://localhost:8000/images/shoe7/shoe7view2.webp', 'http://localhost:8000/images/shoe7/shoe7view3.webp', 'http://localhost:8000/images/shoe7/shoe7view4.webp', 'http://localhost:8000/images/shoe7/shoe7view5.webp','http://localhost:8000/images/shoe7/shoe7view6.webp','http://localhost:8000/images/shoe7/shoe7view7.webp','http://localhost:8000/images/shoe7/shoe7view8.webp'], 'Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colors and crisp leather give it a distinct identity.', 'Shown: Cherrywood Red/Cement Grey/White', 'Style: DQ8426-615', ARRAY ['M 7 / W 8.5','M 7.5 / W 9','M 8 / W 9.5','M 8.5 / W 10','M 9 / W 10.5','M 9.5 / W 11','M 10 / W 11.5','M 10.5 / W 12','M 11 / W 12.5','M 11.5 / W 13','M 12 / W 13.5','M 12.5 / W 14','M 13 / W 14.5','M 14 / W 15.5','M 15 / W 16.5','M 16 / W 17.5','M 17 / W 18.5','M 18 / W 19.5']),
            ('Air Jordan 1 Mid SE', 2, '$135.00', 'Men''s Shoes', 'http://localhost:8000/images/carouselImages/carouselImage1.webp', NULL, NULL, NULL, NULL, NULL),
            ('Air Jordan 1 Mid', 3, '$125.00', 'Women''s Shoes', 'http://localhost:8000/images/carouselImages/carouselImage2.webp', NULL, NULL, NULL, NULL, NULL),
            ('Air Jordan 1 Low', 4, '$110.00', 'Men''s Shoes', 'http://localhost:8000/images/carouselImages/carouselImage3.webp', NULL, NULL, NULL, NULL, NULL),
            ('Air Jordan 1 Zoom CMFT 2', 5, '$150.00', 'Men''s Shoes', 'http://localhost:8000/images/carouselImages/carouselImage4.webp', NULL, NULL, NULL, NULL, NULL),
            ('Air Jordan 1 Retro High OG', 6, '$180.00', 'Men''s Shoes', 'http://localhost:8000/images/carouselImages/carouselImage5.webp', NULL, NULL, NULL, NULL, NULL),
            ('Air Jordan 1 Retro High OG', 7, '$180.00', 'Women''s Shoes', 'http://localhost:8000/images/carouselImages/carouselImage6.webp', NULL, NULL, NULL, NULL, NULL),
            ('Air Jordan 1 Hi FlyEase', 8, '$150.00', 'Men''s Shoes', 'http://localhost:8000/images/carouselImages/carouselImage7.webp', NULL, NULL, NULL, NULL, NULL),
            ('Air Jordan 13 Retro', 9, '$210.00', 'Shoe', 'http://localhost:8000/images/carouselImages/carouselImage8.webp', NULL, NULL, NULL, NULL, NULL),
            ('Jordan 6 Rings', 10, '$144.97', 'Men''s Shoes', 'http://localhost:8000/images/carouselImages/carouselImage9.webp', NULL, NULL, NULL, NULL, NULL),
            ('Jordan Access',11,'$110.00','Men''s Shoe','http://localhost:8000/images/carouselImages/carouselImage10.webp', NULL, NULL, NULL, NULL, NULL),
            ('Nike Air Force 1 ''07',12,'$110.00','Men''s Shoe','http://localhost:8000/images/carouselImages/carouselImage11.webp', NULL, NULL, NULL, NULL, NULL),
            ('Air Jordan 1 Low G',13,'$140.00','Golf Shoes','http://localhost:8000/images/carouselImages/carouselImage12.webp', NULL, NULL, NULL, NULL, NULL)`,
            (err) => {
                if (err) {
                    console.log("INSERT DATA FAILED ON shoes TABLE", err)
                } else {
                    console.log("INSERT DATA INTO shoes SUCCESSFUL")
                    pool.query(`INSERT INTO review (review_id, title, stars, user_name, date_created, summary) VALUES
                    (1, '' ,5, 'Palash544714572', 'Apr 04, 2023', 'I just got my pair 30 minutes ago. They feel great and comfortable. The colorway goes really great with grey hoodies and jeans. In my opinion, this is a fire pair that should be a cop. Plus I have no idea why this is not sold out.'),
                    (1, 'They are dope' ,4, 'Layla322586335', 'Mar 28, 2023', 'I really like these shoes! But they are super narrow. Sometimes they can get uncomfortable but it doesn''t really bother me. They are also pretty durable, but they do crease very easily! Overall the shoes are very nice!'),
                    (1, 'Great shoe' ,5,'Dalove180', 'Mar 20, 2023', '[This review was collected as part of a promotion.] Brought this for my child birthday and she loves it. Product received for free, or reviewed as part of a sweepstakes giveaway. #teamnike'),
                    (2, '' ,5, 'Palash544714572', 'Apr 04, 2023', 'I just got my pair 30 minutes ago. They feel great and comfortable. The colorway goes really great with grey hoodies and jeans. In my opinion, this is a fire pair that should be a cop. Plus I have no idea why this is not sold out.'),
                    (2, 'They are dope' ,4, 'Layla322586335', 'Mar 28, 2023', 'I really like these shoes! But they are super narrow. Sometimes they can get uncomfortable but it doesn''t really bother me. They are also pretty durable, but they do crease very easily! Overall the shoes are very nice!'),
                    (2, 'Great shoe' ,5,'Dalove180', 'Mar 20, 2023', '[This review was collected as part of a promotion.] Brought this for my child birthday and she loves it. Product received for free, or reviewed as part of a sweepstakes giveaway. #teamnike'),
                    (3, 'Dope sneaker' ,5,'Tiri', 'Mar 20, 2023', '[This review was collected as part of a promotion.] I love the colors and it''s so comfortable. True to size Product received for free, or reviewed as part of a sweepstakes giveaway. #teamnike'),
                    (3, 'Great comfort' ,5,'Funki83', 'Mar 17, 2023', 'sehr einfache abwicklung und schnelle lieferung top Great design and love the colors'),
                    (3, 'Great design and love the colors' ,5, 'Banks329', 'Mar 14, 2023', '[This review was collected as part of a promotion.] Bought them for my daughter a month ago and she loves them and the style Product received for free, or reviewed as part of a sweepstakes giveaway. #teamnike'),
                    (4, '' ,5, 'Palash544714572', 'Apr 04, 2023', 'I just got my pair 30 minutes ago. They feel great and comfortable. The colorway goes really great with grey hoodies and jeans. In my opinion, this is a fire pair that should be a cop. Plus I have no idea why this is not sold out.'),
                    (4, 'They are dope' ,4, 'Layla322586335', 'Mar 28, 2023', 'I really like these shoes! But they are super narrow. Sometimes they can get uncomfortable but it doesn''t really bother me. They are also pretty durable, but they do crease very easily! Overall the shoes are very nice!'),
                    (4, 'Great shoe' ,5,'Dalove180', 'Mar 20, 2023', '[This review was collected as part of a promotion.] Brought this for my child birthday and she loves it. Product received for free, or reviewed as part of a sweepstakes giveaway. #teamnike'),
                    (5, '' ,5, 'Palash544714572', 'Apr 04, 2023', 'I just got my pair 30 minutes ago. They feel great and comfortable. The colorway goes really great with grey hoodies and jeans. In my opinion, this is a fire pair that should be a cop. Plus I have no idea why this is not sold out.'),
                    (5, 'They are dope' ,4, 'Layla322586335', 'Mar 28, 2023', 'I really like these shoes! But they are super narrow. Sometimes they can get uncomfortable but it doesn''t really bother me. They are also pretty durable, but they do crease very easily! Overall the shoes are very nice!'),
                    (5, 'Great shoe' ,5,'Dalove180', 'Mar 20, 2023', '[This review was collected as part of a promotion.] Brought this for my child birthday and she loves it. Product received for free, or reviewed as part of a sweepstakes giveaway. #teamnike'),
                    (6, '' ,5, 'MoeM225695270', 'Apr 11, 2023', 'My size is always run out and I really want it'),
                    (6, 'They are dope' ,5, 'Victory932031443', 'Apr 11, 2023', 'They are classy and comfortable to wear.Its able to match with different wear you have .I promise you will not undergo any losses of you buy it'),
                    (6, 'Great shoe' ,4,'reed25011835', 'Apr 07, 2023', 'They are comfortable. I got some good comments on them👍🏻'),
                    (7, '' ,5, 'Palash544714572', 'Apr 04, 2023', 'I just got my pair 30 minutes ago. They feel great and comfortable. The colorway goes really great with grey hoodies and jeans. In my opinion, this is a fire pair that should be a cop. Plus I have no idea why this is not sold out.'),
                    (7, 'They are dope' ,4, 'Layla322586335', 'Mar 28, 2023', 'I really like these shoes! But they are super narrow. Sometimes they can get uncomfortable but it doesn''t really bother me. They are also pretty durable, but they do crease very easily! Overall the shoes are very nice!'),
                    (7, 'Great shoe' ,5,'Dalove180', 'Mar 20, 2023', '[This review was collected as part of a promotion.] Brought this for my child birthday and she loves it. Product received for free, or reviewed as part of a sweepstakes giveaway. #teamnike')`,
                    (err) => {
                        if (err) {
                            console.log("INSERT DATA FAILED ON review", err)
                        } else {
                            console.log("INSERT review DATA SUCCESSFUL")
                            done();
                            callback();
                        }
                    })
                }
            }
        )
    })
}

runSeeder(pool, () => {
    //close connection:
    pool.end();
});

